/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bright_yellow_crayola: "var(--bright-yellow-crayola)",
        medium_turquoise: "var(--medium-turquoise)",
        silver_chalice: "var(--silver-chalice)",
        eerie_black_1: "var(--eerie-black-1)",
        eerie_black_2: "var(--eerie-black-2)",
        eerie_black_3: "var(--eerie-black-3)",
        raisin_black: "var(--raisin-black)",
        granite_gray: "var(--granite-gray)",
        sonic_silver: "var(--sonic-silver)",
        pistachio_50: "var(--pistachio_50)",
        baby_powder: "var(--baby-powder)",
        light_gray: "var(--light-gray)",
        pistachio: "var(--pistachio)",
        platinum: "var(--platinum)",
        cultured: "var(--cultured)",
        white_60: "var(--white-60)",
        white_50: "var(--white_50)",
        white_10: "var(--white_10)",
        white: "var(--white)",
        black: "var(--black)",
        jet: "var(--jet)",
      },
      fontFamily: {
        ff_oswald: "var(--ff-oswald)",
        ff_inter: "var(--ff-inter)",
        ff_roboto: "var(--ff-roboto)",
      },
      fontSize: {
        fs_1: "var(--fs-1)",
        fs_2: "var(--fs-2)",
        fs_3: "var(--fs-3)",
        fs_4: "var(--fs-4)",
        fs_5: "var(--fs-5)",
        fs_6: "var(--fs-6)",
        fs_7: "var(--fs-7)",
        fs_8: "var(--fs-8)",
        fs_9: "var(--fs-9)",
        fs_10: "var(--fs-10)",
      },
      fontWeight: {
        fw_300: "var(--fw-300)",
        fw_500: "var(--fw-500)",
        fw_600: "var(--fw-600)",
        fw_700: "var(--fw-700)",
      },
      boxShadow: {
        cardShadow: "var(--card-shadow)",
      },
      transitionTimingFunction: {
        cubic_in: "var(--cubic-in)",
        cubic_out: "var(--cubic-out)",
      },
    },
    screens: {
      xs: "480px",
      ss: "575px",
      sm: "768px",
      md: "992px",
      lg: "1200px",
    },
  },
  plugins: [],
};
